export { default as FormTemplate } from './FormTemplate'
export { default as Navbar } from './Navbar'
export { default as ResetPassword } from './ResetPassword'
export { default as ForgotPassword } from './ForgotPassword'
export { default as Shoppers } from './Shoppers'
export { default as Documents } from './Documents'
export { default as Dashboards } from './Dashboards'